language: c

compiler:
    - gcc
    - clang

env:
    - OPTIONS="-DCMAKE_BUILD_TYPE=Debug"
    - OPTIONS="-DCMAKE_BUILD_TYPE=MinSizeRel"
    - OPTIONS="-DCMAKE_BUILD_TYPE=Release"

# Make sure CMake is installed
install:
    - sudo apt-get update >/dev/null
    - sudo apt-get -q install cmake libgtk2.0-dev libglib2.0-dev libnotify-dev libcanberra-dev

script:
    - cd build
    - cmake .. -DCMAKE_INSTALL_PREFIX=../_install $OPTIONS
    - cmake --build . --target install
